---
kind: pipeline
type: exec
name: default

platform:
 os: linux
 arch: amd64

trigger:
  event:
    include:
    - push
    - custom

steps:
- name: Build
  commands:
  - nix develop --command ./gradlew build
- name: Test
  commands:
  - nix develop --command ./gradlew jar
...
