---
kind: pipeline
type: exec
name: default

platform:
 os: linux
 arch: amd64

trigger:
  event:
    include:
    - push
    - custom

steps:
- name: build and test
  commands:
  - gradle build
- name: package jar
  commands:
  - gradle jar
...
