package com.riscure.langs.c

import arrow.core.*
import com.riscure.tc.codeanalysis.clang.ast.loader.ClangParsingResult
import com.riscure.tc.codeanalysis.clang.compiler2.loader.CompileCommandMapping
import org.bytedeco.javacpp.*
import org.bytedeco.llvm.clang.*
import org.bytedeco.llvm.global.clang
import org.bytedeco.llvm.global.clang.*
import org.bytedeco.llvm.global.clang.clang_parseTranslationUnit2 as clang_parse
import java.io.File

/**
 * This implements the parser interface using the Bytedeco library to call
 * into libclang to parse a C file.
 *
 * This is *not* thread-safe.
 */
class ClangParser(val ccMap : CompileCommandMapping = CompileCommandMapping()): Parser {

    override fun parse(file: File): Result<TranslationUnit> {
        val args: Array<String> = arrayOf("")

        // We allocate the arguments.
        val c_index: CXIndex = clang.clang_createIndex(0, 0)
        val c_tu = CXTranslationUnit()
        val c_sourceFile = BytePointer(file.absolutePath.toString())
        val c_arg_pointers = args.map { BytePointer(it) }
        val c_args = PointerPointer<BytePointer>(args.size.toLong())
        val c_parseOptions = clang.CXTranslationUnit_SingleFileParse

        c_arg_pointers.forEach { c_args.put(it) }

        // Define the deallocator
        fun free() {
            clang.clang_disposeIndex(c_index)
            clang.clang_disposeTranslationUnit(c_tu)
            c_sourceFile.close()
            c_arg_pointers.forEach { it.deallocate() }
            c_args.deallocate()
        }

        // Call into libclang via bytedeco
        val code: Int = clang_parse(c_index, c_sourceFile, c_args, args.size, null, 0, c_parseOptions, c_tu)

        try {
            // Interpret the result code generated by clang:
            val result = ClangParsingResult.fromCode(code)
            return if (result != ClangParsingResult.Success) {
                result.message.left()
            } else {
                // transform the translation unit outputted by clang to a real Java AST object
                val c_tuCursor = clang.clang_getTranslationUnitCursor(c_tu)
                return c_tuCursor.asTranslationUnit()
            }
        } finally { free() }
    }
}

// We define extension functions for CXCursors that translate to the AST
// All these translations are partial, because they validate structure that is
// not apparent through the visitor API of libclang.

fun CXCursor.children(): List<CXCursor> {
    val cs = mutableListOf<CXCursor>()

    clang_visitChildren(
        this,
        object: CXCursorVisitor() {
            override fun call(self: CXCursor?, parent: CXCursor?, p2: CXClientData?): Int {
                cs.add(self!!)
                return CXChildVisit_Continue
            }
        },
        null)

    return cs
}

fun CXCursor.kind() = clang_getCursorKind(this)
fun CXCursor.spelling(): String = clang_getCursorSpelling(this).string

fun CXCursor.asTranslationUnit(): Result<TranslationUnit> {
    if (this.kind() != CXCursor_TranslationUnit) {
        return "Expected translation unit, got cursor of kind $this.kind()".left()
    }

    return this.children()
        .map { it.asGlobalDecl() }
        .sequenceEither()
        .map { TranslationUnit(it) }
}

fun CXCursor.asGlobalDecl(): Result<GlobalDecl> {
    return when (this.kind()) {
        CXCursor_FunctionDecl -> this.asFunctionDecl()
        else -> "Expected global declaration".left()
    }
}

fun CXCursor.asFunctionDecl(): Result<GlobalDecl.Fun> {
    if (kind() != CXCursor_FunctionDecl) {
        return "Expected function declaration, got cursor of kind ${kind()}".left()
    }

    val nargs = clang_Cursor_getNumArguments(this)
    return (0 until nargs)
        .map { clang_Cursor_getArgument(this, it) }
        .map { it.asParam() }
        .sequenceEither()
        .map { params ->
            GlobalDecl.Fun(false, spelling(), Type.Void(), params)
        }

}

fun CXCursor.asParam(): Result<Param> {
    if (kind() != CXCursor_ParmDecl) {
        return "Exepected parameter declaration".left()
    }

    return Param(spelling()).right()
}